import fourStar from './image/4star.png';
import threeStar from './image/3star.png';
import mumbai2 from "./image/mumbai2.jpg"
import mumbai1 from "./image/mumbai1.jpg"
import Hyderabad from './image/Hyderabad.jpg';
import Banglore1 from './image/Banglore1.jpg';
import banglore4 from './image/banglore4.jpg';
import Banglore2 from './image/Banglore2.jpg';
import Banglore3 from './image/Banglore3.jpg';
import Jaipur1 from './image/Jaipur1.jpg';
import Jaipur2 from './image/Jaipur2.jpg';
import Banglore5 from './image/Banglore5.jpg';
import Chennai from './image/Chennai.jpg';
import Kerala4 from './image/Kerala4.jpg';
import Kerala9 from './image/Kerala9.jpg';
import Kerala3 from './image/Kerala3.jpg';
import kerala2 from './image/kerala2.jpg';
import Kerala1 from './image/Kerala1.jpg';
import Chennai3 from './image/Chennai3.jpg';
import Chennai2 from './image/Chennai2.jpg';
import Delhi3 from './image/Delhi3.jpg';
import Delhi1 from './image/Delhi1.jpg';
import punjab1 from './image/punjab1.jpg';
import Punjab2 from './image/Punjab2.jpg';
import punjab3 from './image/punjab3.jpg';
import Kolkatta from './image/Kolkatta.jpg';

export const ProductsData = [
  {
    id: 1,
    name: 'Volleyball',
    date: '2024-07-20',
    image: Delhi1,
    location: 'Delhi',
    mapName: 'img1',
    mapLink: 'https://maps.app.goo.gl/G4yq3L7NpGMifcKfA',
    fieldName: 'Volleyball Field',
    address: 'Suraj Bhan DAV Public School, Poorvi Marg, New Delhi, Delhi 110057',
    sports: ['Tennis', 'Volleyball'],
    amount: '8500',
    ratingImage: threeStar,
  },
  {
    id: 2,
    name: 'Football',
    date: '2024-07-20',
    image: Banglore1,
    location: 'Banglore',
    mapName: 'img2',
    mapLink: 'https://maps.app.goo.gl/ope8QE2nCqu7y2Lr9',
    fieldName: 'Football Field',
    address: 'Royal Towers Hennur RingRoad Junction Kalyan Nagar, Bengaluru',
    sports: ['Tennis', 'Volleyball'],
    amount: '6500',
    ratingImage: threeStar,
  },
  {
    id: 3,
    name: 'Cricket',
    date: '2024-07-20',
    image: banglore4,
    location: 'Banglore',
    mapName: 'img3',
    mapLink: 'https://maps.app.goo.gl/G4yq3L7NpGMifcKfA',
    fieldName: 'Cricket Field',
    address: 'Suraj Bhan DAV Public School, Poorvi Marg, New Delhi, Delhi 110057',
    sports: ['Football', 'Cricket'],
    amount: '8500',
    ratingImage: fourStar,
  },
  {
    id: 4,
    name: 'Football',
    date: '2024-07-20',
    image: Banglore2,
    location: 'Jaipur',
    mapName: 'img4',
    mapLink: 'https://maps.app.goo.gl/YNedziv2VaXaoyxw6',
    fieldName: 'Football Field',
    address: 'Jan Path, Pratik Nagar, Jhotwara, Jaipur, Rajasthan 302012',
    sports: ['Tennis', 'Volleyball'],
    amount: '8500',
    ratingImage: fourStar,
  },
  {
    id: 5,
    name: 'Football',
    date: '2024-07-20',
    image: Banglore3,
    location: 'Banglore',
    mapName: 'img5',
    mapLink: 'https://maps.app.goo.gl/hvb2rDmqSQqYgeGA6',
    fieldName: 'Football Field',
    address: 'Chapparadahalli, Near GITAM University Banglore',
    sports: ['Tennis', 'Volleyball'],
    amount: '7500',
    ratingImage: threeStar,
  },
  {
    id: 6,
    name: 'Football',
    date: '2024-07-20',
    image: Banglore5,
    location: 'Chennai',
    mapName: 'img6',
    mapLink: 'https://maps.app.goo.gl/V6V6RGuEay4rCe5D7',
    fieldName: 'Football Field',
    address: '47, Bajanai Koil Street, RK Link Rd, Villivakkam, Chennai, Tamil Nadu',
    sports: ['Tennis', 'Volleyball'],
    amount: '8500',
    ratingImage: threeStar,
  },
  {
    id: 7,
    name: 'Football',
    date: '2024-07-20',
    image: Delhi3,
    location: 'Delhi',
    mapName: 'img8',
    mapLink: 'https://maps.app.goo.gl/Qhu8feb8CGAAZNhw5',
    fieldName: 'Football Field',
    address: 'Summer Fields School, Greater Kailash-1 Kailash Colony, Greater Kailash',
    sports: ['Tennis', 'Volleyball'],
    amount: '8500',
    ratingImage: threeStar,
  },
  {
    id: 8,
    name: 'Football',
    date: '2024-07-20',
    image: punjab1,
    location: 'Delhi',
    mapName: 'img9',
    mapLink: 'https://maps.app.goo.gl/zMuiVeoEtDNm7u5P6',
    fieldName: 'Football Field',
    address: 'Farm 31, 100 Feet Rd, Ghitorni, New Delhi, Delhi',
    sports: ['Tennis', 'Football'],
    amount: '8500',
    ratingImage: threeStar,
  },
  {
    id: 9,
    name: 'Football',
    date: '2024-07-20',
    image: Punjab2,
    location: 'Punjab',
    mapName: 'img10',
    mapLink: 'https://maps.app.goo.gl/dMc44rP69JoVY4Xq9',
    fieldName: 'Football Field',
    address: 'MVC7+XHC, Loharka Rd, Gumtala Sub Urban Ranjit Vihar, Nanngli, Amritsar',
    sports: ['Football', 'Volleyball'],
    amount: '8000',
    ratingImage: threeStar,
  },
  {
    id: 10,
    name: 'Football',
    date: '2024-07-20',
    image: punjab3,
    location: 'Patna',
    mapName: 'img11',
    mapLink: 'https://maps.app.goo.gl/uNnfMQRHAn91LLei9',
    fieldName: 'Football Field',
    address: 'Polson Road, beside Modern School, Yadav Colony, Digha Ghat, Patna',
    sports: ['Tennis', 'Football'],
    amount: '7000',
    ratingImage: threeStar,
  },
  {
    id: 11,
    name: 'Cricket',
    date: '2024-07-20',
    image: Kolkatta,
    location: 'Kolkatta',
    mapName: 'img12',
    mapLink: 'https://maps.app.goo.gl/agasvs6drTnoxWRW9',
    fieldName: 'Cricket Field',
    address: 'Acharya Jagdish Chandra Bose Rd, Maidan, Race Course, Hastings, Kolkata',
    sports: ['Tennis', 'Volleyball'],
    amount: '8500',
    ratingImage: threeStar,
  },
  {
    id: 12,
    name: 'Football',
    date: '2024-07-20',
    image: Kerala9,
    location: 'Delhi',
    mapName: 'img13',
    mapLink: 'https://maps.app.goo.gl/qEN8T4xnYuh3fbJZ9',
    fieldName: 'Football Field',
    address: 'inside Ramjas Sports Complex, Block 36, West Patel Nagar, Patel Nagar, Delhi',
    sports: ['Tennis', 'Volleyball'],
    amount: '7500',
    ratingImage: threeStar,
  },
  {
    id: 13,
    name: 'Football',
    date: '2024-07-20',
    image: Hyderabad,
    location: 'Patna',
    mapName: 'img14',
    mapLink: 'https://maps.app.goo.gl/jxNCMiRfdCrds2PT8',
    fieldName: 'Football Field',
    address: 'Polson Dairy Road, near Patliputra Rail-Parisar, Nirala Nagar, Birla Colony',
    sports: ['Tennis', 'Football'],
    amount: '7500',
    ratingImage: threeStar,
  },
  {
    id: 14,
    name: 'Football',
    date: '2024-07-20',
    image: Hyderabad,
    location: 'Patna',
    mapName: 'img15',
    mapLink: 'https://maps.app.goo.gl/Wdf3jnWmpHDJwKZL7',
    fieldName: 'Football Field',
    address: 'Atal Path, Yadav Colony, Digha Ghat, Patna, Bihar 800011',
    sports: ['Tennis', 'Football'],
    amount: '7500',
    ratingImage: threeStar,
  },
  {
    id: 15,
    name: 'Football',
    date: '2024-08-20',
    image: mumbai2,
    location: 'Mumbai',
    mapName: 'img16',
    mapLink: 'https://maps.app.goo.gl/eqQdPuzZ7s32hwSB6',
    fieldName: 'Football Field',
    address: 'Royal Western India Turf Club, Mahalakshmi Mumbai, Maharashtra',
    sports: ['Football', 'Volleyball'],
    amount: '7500',
    ratingImage: threeStar,
  },
  {
    id: 16,
    name: 'Basketball',
    date: '2024-07-20',
    image: mumbai1,
    location: 'Mumbai',
    mapName: 'img17',
    mapLink: 'https://maps.app.goo.gl/2HRREx6N2cLQuQY57',
    fieldName: 'Basketball Field',
    address: 'Atal Path, Yadav Colony, Digha Ghat, Patna, Bihar 800011',
    sports: ['Tennis', 'Football', 'Basketball'],
    amount: '7500',
    ratingImage: threeStar,
  },
  {
    id: 17,
    name: 'Volleyball',
    date: '2024-07-20',
    image: Chennai3,
    location: 'Chennai',
    mapName: 'img18',
    mapLink: 'https://maps.app.goo.gl/V6V6RGuEay4rCe5D7',
    fieldName: 'Volleyball Field',
    address: '47, Bajanai Koil Street, RK Rd, Thathan Kuppam, Villivakkam',
    sports: ['Tennis', 'Volleyball'],
    amount: '8500',
    ratingImage: threeStar,
  },
  {
    id: 18,
    name: 'Cricket',
    date: '2024-07-20',
    image: Chennai2,
    location: 'Chennai',
    mapName: 'img19',
    mapLink: 'https://maps.app.goo.gl/DhFQ6W9rviNuzGiq6',
    fieldName: 'Cricket Field',
    address: 'Thiruvottiyur High Rd, Kasipuram, Tondiarpet, Chennai',
    sports: ['Tennis', 'Volleyball'],
    amount: '8500',
    ratingImage: threeStar,
  },
  {
    id: 19,
    name: 'Cricket',
    date: '2024-07-20',
    image: Chennai,
    location: 'Chennai',
    mapName: 'img20',
    mapLink: 'https://maps.app.goo.gl/Ar4hRGtGUs5mLobQ9',
    fieldName: 'Cricket Field',
    address: 'Moolachathiram road, Krishna Nagar, Madhavaram Milk Colony',
    sports: ['Football', 'Cricket'],
    amount: '7500',
    ratingImage: threeStar,
  },
  {
    id: 20,
    name: 'Cricket',
    date: '2024-07-20',
    image: Kerala4,
    location: 'Kerala',
    mapName: 'img21',
    mapLink: 'https://maps.app.goo.gl/YNedziv2VaXaoyxw6',
    fieldName: 'Cricket Field',
    address: 'Kottakuziyil, Kottayam, Kerala 587906',
    sports: ['Cricket', 'Volleyball'],
    amount: '6500',
    ratingImage: threeStar,
  },
  {
    id: 21,
    name: 'Cricket',
    date: '2024-07-20',
    image: Kerala3,
    location: 'Kerala',
    mapName: 'img22',
    mapLink: 'https://maps.app.goo.gl/yvXdUYCSnNxVxPbU9',
    fieldName: 'Cricket Field',
    address: '78C6+25X, Kadukutty, Kerala 680309',
    sports: ['Football', 'Cricket'],
    amount: '7500',
    ratingImage: threeStar,
  },
  {
    id: 22,
    name: 'Volleyball',
    date: '2024-07-20',
    image: kerala2,
    location: 'Kerala',
    mapName: 'img23',
    mapLink: 'https://maps.app.goo.gl/qz4L2ympbq56LCWR7',
    fieldName: 'Volleyball Field',
    address: '78C6+25X, Kadukutty, Kerala 680309',
    sports: ['Tennis', 'Volleyball'],
    amount: '6500',
    ratingImage: fourStar,
  },
  {
    id: 23,
    name: 'Volleyball',
    date: '2024-07-20',
    image: Kerala1,
    location: 'Kerala',
    mapName: 'img24',
    mapLink: 'https://maps.app.goo.gl/ezWNbnojum4UC5iS7',
    fieldName: 'Volleyball Field',
    address: 'QJX6+JWQ, Uzhavoor-Koothattukulam Rd, Uzhavoor, Kerala 686634',
    sports: ['Tennis', 'Volleyball'],
    amount: '7500',
    ratingImage: fourStar,
  },
  {
    id: 24,
    name: 'Volleyball',
    date: '2024-07-20',
    image: Jaipur2,
    location: 'Jaipur',
    mapName: 'img24',
    mapLink: 'https://maps.app.goo.gl/mNqnoLf9QESSS4eJA',
    fieldName: 'Volleyball Field',
    address: '25/14 Regal Sports Club Opp- Rangoli Garden, Maharana Pratap Road',
    sports: ['Tennis', 'Volleyball'],
    amount: '7500',
    ratingImage: fourStar,
  },
  {
    id: 25,
    name: 'Volleyball',
    date: '2024-07-20',
    image: Jaipur1,
    location: 'Jaipur',
    mapName: 'img24',
    mapLink: 'https://maps.app.goo.gl/aSBh6ZjvQC6xnUBE9',
    fieldName: 'Volleyball Field',
    address: 'Ganesh Nagar - II, near Coaching hub, Sheopur, Jagatpura, Jaipur',
    sports: ['Tennis', 'Volleyball'],
    amount: '8500',
    ratingImage: fourStar,
  },
];
